### ISSUE TITLE
Port Duplicated in Graph Title

### ISSUE THREAD

**Issue by eanmclaughlin** [winny-/mcstat#1]
As shown here: http://games.snowmew.tk/stats/snowmew.tk/games.snowmew.tk/minecraft_users_games_snowmew_tk_25565.html the port number is displayed twice in the title of the graph.
The file in `/etc/munin/plugins` is named `minecraft_users_games.snowmew.tk:25565` (I couldn't get it to work without adding the port even though it's on the default and I saw regex for checking that in the program when I skimmed over it).

**Comment by winny-** [comment]
Hey! Thank you for reporting.

Can you gist your `phpinfo()`? From your server's shell:

``` text
$ php -a
> echo phpinfo();
```

**Comment by winny-** [comment]
Nevermind `phpinfo()`. Please try commit 033108100ff1e834b27bea4735d0f1da58098394 on branch [fixPluginAutoconfig](https://github.com/winny-/mcstat/tree/fixPluginAutoconfig).

**Comment by eanmclaughlin** [comment]
Yep, that fixed it. Working great without port in file name and only showing it once in the graph title.

Thanks!

**Comment by winny-** [comment]
:cake: Glad to hear it!
